version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/var/www/html

  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  db:
    build: ./infra/mysql
    ports:
      - 3006:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: